### PR TITLE
Update default.html

### PR DESCRIPTION
**Pull request by ben-dasilva**
Fixed typo in Facebook URL in footer section of home page.

### CODE REVIEW

**Comment by ben-dasilva** [comment]
Sorry about accidentally closing and reopening this Pull Request (it's my first one). I hope it can be useful.  Best regards,
- Ben

**Comment by saracope** [comment]
Awesome! Will take a look at it today. 👍

**Comment by saracope** [comment]
Thank you!

**Comment by saracope** [comment]
Closes #103

**Pull request merged**
