### PR TITLE
changes for #66: added aria-link to the links

### PR DESCRIPTION
**Pull request by spiraldancer**

### CODE REVIEW

**Comment by kcjonesevans** [comment]
This is going to throw a bunch of errors! 
Once generated the aria-label isn't in quotes:
`aria-label=Intermediate JavaScript`
needs to generate like this:
`aria-label="Intermediate JavaScript"`

**Comment by spiraldancer** [comment]
fixed the bug. Sorry I missed they weren't in quotes.

**Comment by spiraldancer** [comment]
I am not sure if I need to resolve the mentioned merge conflicts prior to the pull request for the bug fix.  Do I?

**Comment by kcjonesevans** [comment]
You need to update your repo since there have been a lot of changes on the site from all the other prs. That will fix the merge issues, check out https://help.github.com/articles/syncing-a-fork/ if you have questions checkout the hacktoberfest slack channel (its come up a few times)

**Comment by spiraldancer** [comment]
Thanks, I just wanted to confirm.

And I am still getting use to slack. Yes I should have checked there first.
Thanks for the reminder! :-)

On Oct 19, 2017 11:08 AM, "K.C. Jones-Evans" <notifications@github.com>
wrote:

You need to update your repo since there have been a lot of changes on the
site from all the other prs. That will fix the merge issues, check out
https://help.github.com/articles/syncing-a-fork/ if you have questions
checkout the hacktoberfest slack channel (its come up a few times)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/gdidayton/gdidayton/pull/74#issuecomment-337936319>,
or mute
the thread

**Pull request closed without merging**
